server:
  port: 8099
  servlet:
    context-path: /wht_fcw

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_shangcheng?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  #最大连接数
    maxActive: 30
  #最小连接数
    minIdle: 5
  #获取连接得最大等待时间
    maxWait: 10000
  #解决mysql8小时问题
    validationQuery: SELECT 'X'
  #空闲连接检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
  #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000
  application:
    name: wht_fcw
#  datasource:
#    name: mysql
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/springcloud_shangcheng?useSSL=false&serverTimezone=HongKong&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
 #     idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
logging:
  config: classpath:log4j2.xml



mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml